# some more ls aliases
alias ll='ls -lh'
alias la='ls -lha'
alias lsa='ls -a'
alias l='ls -CF'
alias em='emacs -nw'
alias dd='dd status=progress'
alias _='sudo'
alias _i='sudo -i'
alias _aggiorna='sudo yaourt -Syu'
alias _installa='sudo yaourt -S'
alias _rimuovi='sudo yaourt -R'
alias aggiorna='yaourt -Syu'
alias installa='yaourt -S'
alias rimuovi='yaourt -R'
alias cls='clear'
alias gg='neofetch'
alias xx='exit'
